<?php
defined('BASEPATH') or exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try guess the protocol and path
| your installation, but due to security concerns the hostname will be set
| to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = 'http://localhost/siak_sdit';
// $config['base_url'] = 'http://' . $_SERVER['HTTP_HOST'] . '/' . basename(getcwd());
// $config['base_url'] = 'http://localhost/stfms.vadhana.co.id/';
// $config['base_url'] = 'http://192.168.1.203:83';
// $config['base_url'] = 'http://localhost/SCM';
// $config['base_url'] = 'http://stfms.local';
// $config['base_url'] = 'http://192.168.1.205/SCM';
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol'] = 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/urls.html
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language'] = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/user_guide/general/core_classes.html
| https://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = 'vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/user_guide/libraries/encryption.html
|
*/
// $config['encryption_key'] = 'VadhanaGroup';
$config['encryption_key'] = 'dwdad213213dwawd213132e1eawdqevvEAXDAWD123';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = sys_get_temp_dir();
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix'] = '';
$config['cookie_domain'] = '';
$config['cookie_path'] = '/';
$config['cookie_secure'] = FALSE;
$config['cookie_httponly'] = FALSE;

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
//$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'csrf_scm';
$config['csrf_cookie_name'] = 'csrf_cookie_scm';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array(
  'lawang/switchAccount',

  # spadmin
  'spadmin/manage_item/list',
  'spadmin/manage_karyawan/list',
  'spadmin/log/list',
  'spadmin/manage_bank/list',
  'spadmin/manage_rekening/list',
  'spadmin/manage_backdate/list',
  'spadmin/manage_rek_perusahaan/list',
  'spadmin/manage_supplier/list',
  'spadmin/manage_customer/list',
  'spadmin/manage_kategori/list',
  'spadmin/manage_kurs/list',
  'spadmin/manage_currency/list',
  'spadmin/manage_itemdetail/list',
  'spadmin/manage_stokitem_wh/list',
  'spadmin/manage_stokitem_pr/list',
  'spadmin/manage_stokopname/list',
  'spadmin/manage_adjuststok/list',
  'spadmin/manage_warehouse/list',
  'spadmin/monitoring_karyawan/list',
  'spadmin/monitoring_team/list',
  'spadmin/monitoring_job/list',
  'spadmin/manage_teamanggota/approval/list',
  'spadmin/manage_mr/list/.*+',
  'spadmin/manage_mrclose/list.*+',
  'spadmin/manage_pr/list1',
  'spadmin/manage_pr/list2',
  'spadmin/manage_pr/list3',
  'spadmin/manage_penawaran/list',
  'spadmin/manage_item_for_po/list/.*+',
  'spadmin/manage_item_for_po/list4/Claimed',
  'spadmin/manage_po/list',
  'spadmin/manage_item_po/list/.*+',
  'spadmin/manage_fat/list1/InvToFat',
  'spadmin/manage_fat/list/.*+',
  'spadmin/manage_fat/list2',
  'spadmin/manage_mi/list1',
  'spadmin/manage_mi/list2',
  'spadmin/manage_mi/list3',
  'spadmin/manage_mo/list1',
  'spadmin/manage_mo/list2/Pending',
  'spadmin/manage_mo/list2',
  'spadmin/manage_mt/list/.*+',
  'spadmin/manage_retur_mo/list/.*+',
  'spadmin/manage_retur_po/list/.*+',
  'spadmin/manage_prremove/list',
  'spadmin/notifikasi/list',
  'spadmin/manage_satuan/list',
  'spadmin/manage_konversi/list/.*+',
  'spadmin/manage_invoice/list1/DokToBeInv',
  'spadmin/manage_invoice/list/.*+',
  'spadmin/manage_pengguna/list',
  'spadmin/manage_referensi/jenis_dokumen/list',
  'spadmin/manage_paccount/list',
  'spadmin/manage_release_giro/list/.*+',
  'spadmin/manage_do/list/.*+',
  'spadmin/manage_job/list',
  'spadmin/manage_currencylimit/list/.*+',
  'spadmin/manage_ttdokumen/list1',
  'spadmin/manage_ttdokumen/list2',
  'spadmin/manage_teamproject/list',
  'spadmin/manage_teamproject/list/.*+',
  'spadmin/manage_waccount/list/.*+',
  'spadmin/monitoring_fat_detail/list',
  'spadmin/monitoring_item_mi/list',
  'spadmin/monitoring_item_mo/list',
  'spadmin/monitoring_do_detail/list',
  'spadmin/manage_po/add',
  'spadmin/manage_item_for_po/list5',
  'spadmin/approval_pembayaran/list/.*+',
  'spadmin/bankpayment/list/.*+',
  'spadmin/lp_rencana_pembayaran/getlaporan',
  'spadmin/manage_dokumen/list',
  'spadmin/kategori_dokumen/list',
  'spadmin/subkategori_dokumen/list',
  'spadmin/manage_dokumen/listDok/.*+',
  'spadmin/dokumen_permission/listData/.*+',
  'spadmin/logdokumen/list/.*+',
  'spadmin/logdokumen/grafik/.*+',
  'spadmin/manage_dokumen_admin/list',
  'spadmin/manage_other_charge/list',
  'spadmin/manage_sub_item/list',
  'spadmin/manage_coa/list',
  'spadmin/manage_cad/list',
  'spadmin/manage_exr/list',
  'spadmin/manage_exr/list2',
  'spadmin/manage_exr/list3',
  'spadmin/manage_rfp/list',
  'spadmin/manage_rfp/list2',
  'spadmin/manage_rfp_kasbesar/list',
  'spadmin/manage_rfp_kasbesar/list2',
  'spadmin/manage_picppbank/list',
  'spadmin/manage_limitcad/list',
  'spadmin/manage_pettycash/list',
  'spadmin/manage_tp_pettycash/list',
  'spadmin/manage_kas/list',
  'spadmin/manage_periodeakuntansi/list',
  'spadmin/manage_kegiatan/list',
  'spadmin/manage_transaksi/list/.*+',
  'spadmin/manage_jurnal/list',
  'spadmin/manage_jurnal/list2',
  'spadmin/manage_pcoa/list',
  'spadmin/monitoring_dokumen_kasbank/list/.*+',
  'spadmin/manage_ptax/list',
  'spadmin/manage_jurnal_umum/list',
  'spadmin/close_po/list/.*+',
  'spadmin/manage_perusahaan/list/.*+',
  'spadmin/monitoring_ca_will_lpj/list',
  'spadmin/manage_bukubillyet/list',
  'spadmin/manage_billyet/list/.*+',
  'spadmin/manage_billyet/list2/.*+',
  'spadmin/manage_invoice_sales/list',
  'spadmin/manage_progress/list',
  'spadmin/manage_item_kegiatan/list',
  'spadmin/manage_saldoawal/list',

  # purchasing
  'purchasing/manage_item/list',
  'purchasing/manage_itemdetail/list',
  'purchasing/manage_konversi/list/.*+',
  'purchasing/manage_supplier/list/.*',
  'purchasing/monitoring_team/list',
  'purchasing/monitoring_job/list',
  'purchasing/manage_itemstok/list',
  'purchasing/manage_bank/list',
  'purchasing/manage_rekening/list',
  'purchasing/approval_mr/list/.*+',
  'purchasing/approval_pr/list/.*+',
  'purchasing/approval_po/list/.*+',
  'purchasing/approval_supplier/list/.*+',
  'purchasing/manage_pr/list',
  'purchasing/manage_prremove/list',
  'purchasing/manage_penawaran/list',
  'purchasing/manage_item_for_po/list/.*+',
  'purchasing/manage_item_for_po/list4/Claimed',
  'purchasing/manage_po/list',
  'purchasing/manage_item_po/list/.*+',
  'purchasing/notifikasi/list',
  'purchasing/notifikasi/cek_notif',
  'purchasing/notifikasi/update_status',
  'purchasing/manage_konversi/list/.*+',
  'purchasing/manage_stokitem_wh/list',
  'purchasing/manage_stokitem_pr/list',
  'purchasing/manage_invoice/list1/DokToBeInv',
  'purchasing/manage_invoice/list/.*+',
  'purchasing/manage_referensi/jenis_dokumen/list',
  'purchasing/manage_ttdokumen/list1',
  'purchasing/manage_ttdokumen/list2',
  'purchasing/monitoring_pr/list',
  'purchasing/monitoring_po/list',
  'purchasing/monitoring_mr/list/.*+',
  'purchasing/manage_item_pr/list/All',
  'purchasing/manage_kategori/list',
  'purchasing/manage_subkategori/list',
  'purchasing/manage_po/add',
  'purchasing/manage_item_for_po/list5',
  'purchasing/manage_retur_po/list/.*+',
  'purchasing/manage_sub_item/list',
  'purchasing/manage_other_charge/list',
  'purchasing/monitoring_fat_detail/list',
  'purchasing/close_po/list/.*+',
  'purchasing/approval_closepo/list/.*+',
  'purchasing/manage_customer/list',

  # staff
  'staff/manage_mi/list/.*+',
  'staff/manage_mi/list',
  'staff/manage_mo/list/Approval',
  'staff/manage_wmo/list/Approved',
  'staff/manage_mo/list',
  'staff/manage_mr/list/.*+',
  'staff/manage_mrclose/list/.*+',
  'staff/manage_pr/list',
  'staff/approval_mr/list/.*+',
  'staff/approval_pr/list/.*+',
  'staff/approval_po/list/.*+',
  'staff/approval_fat/list/.*+',
  'staff/approval_mi/list/.*+',
  'staff/approval_mo/list/.*+',
  'staff/approval_prremove/list',
  'staff/notifikasi/list',
  'staff/notifikasi/cek_notif',
  'staff/notifikasi/update_status',
  'staff/monitoring_team/list',
  'staff/monitoring_rental_asset/list',
  'staff/manage_asset/list',
  'staff/approval_prremove/list/.*+',
  'staff/monitoring_mr/list/.*+',
  'staff/manage_dokumen/list',
  'staff/kategori_dokumen/list',
  'staff/subkategori_dokumen/list',
  'staff/manage_dokumen/listDok/.*+',
  'staff/dokumen_permission/listData/.*+',
  'staff/logdokumen/list/.*+',
  'staff/logdokumen/grafik/.*+',
  'staff/dokumen_request/list/.*+',
  'staff/dokumen_request/listconfirm/.*+',
  'staff/request_layanan/list/.*+',
  'staff/manage_notifikasi/list',
  'staff/request_approve/list/.*+',
  'staff/manage_cad/list',
  'staff/approval_cad/list/.*+',
  'staff/manage_exr/list',
  'staff/manage_exr/list2',
  'staff/manage_exr/list3',
  'staff/manage_exr/save',
  'staff/approval_exr/list/.*+',
  'staff/manage_rfp/list',
  'staff/manage_rfp/list2',
  'staff/manage_rfp/save',
  'staff/approval_rfp/list/.*+',
  'staff/manage_rfp_kasbesar/list',
  'staff/manage_rfp_kasbesar/list2',
  'staff/approval_rfp_kasbesar/list/.*+',
  'staff/manage_pettycash/list',
  'staff/manage_pettycash/list2',
  'staff/approval_pettycash/list/.*+',
  'staff/approval_transaksi/list/.*+',
  'staff/konfirmasi_invoice/list',
  'staff/konfirmasi_progress/list',
  'staff/manage_progress/list',
  'staff/approval_cash_payment/list/.*+',
  'staff/approval_cash_receive/list/.*+',
  'staff/approval_bank_payment/list/.*+',
  'staff/approval_bank_receive/list/.*+',
  'staff/manage_rfp_payroll/save',

  # warehouse
  'warehouse/manage_customer/list',
  'warehouse/monitoring_job/list',
  'warehouse/monitoring_team/list',
  'warehouse/manage_kategori/list',
  'warehouse/manage_stokitem_wh/list',
  'warehouse/manage_stokitem_pr/list',
  'warehouse/approval_mt/list/.*+',
  'warehouse/manage_mr/list',
  'warehouse/manage_pr/list1',
  'warehouse/manage_pr/list2',
  'warehouse/manage_pr/list3',
  'warehouse/manage_mi/list1',
  'warehouse/manage_mi/list2',
  'warehouse/manage_mi/list3',
  'warehouse/manage_mi/list4',
  'warehouse/manage_mo/list1',
  'warehouse/manage_mo/list2/Pending',
  'warehouse/manage_mo/list2',
  'warehouse/manage_mo/list3',
  'warehouse/manage_mt/list/.*+',
  'warehouse/approval_mr/list/.*+',
  'warehouse/approval_pr/list/.*+',
  'warehouse/approval_mi/list/.*+',
  'warehouse/approval_mo/list/.*+',
  'warehouse/approval_rpo/list/.*+',
  'warehouse/approval_prremove/list/.*+',
  'warehouse/notifikasi/list',
  'warehouse/notifikasi/cek_notif',
  'warehouse/notifikasi/update_status',
  'warehouse/manage_retur_mo/list/.*+',
  'warehouse/manage_retur_po/list/.*+',
  'warehouse/manage_do/list/.*+',
  'warehouse/approval_do/list/.*+',
  'warehouse/monitoring_pr/list',
  'warehouse/monitoring_po/list',
  'warehouse/monitoring_mr/list/.*+',
  'warehouse/manage_item_po/list/.*+',
  'warehouse/manage_item_pr/list/All',
  'warehouse/monitoring_item_mi/list',
  'warehouse/monitoring_item_mo/list',
  'warehouse/monitoring_do_detail/list',
  'warehouse/manage_adjuststok/list',
  'warehouse/manage_assembly/list',
  'warehouse/approval_assembly/list/.*+',
  'warehouse/manage_itemdetail/list',

  # Finance
  'finance/manage_kurs/list',
  'finance/monitoring_job/list',
  'finance/monitoring_team/list',
  'finance/notifikasi/list',
  'finance/notifikasi/cek_notif',
  'finance/notifikasi/update_status',
  'finance/manage_bank/list',
  'finance/approval_stokopname/list/.*+',
  'finance/approval_adjuststok/list/.*+',
  'finance/approval_mr/list/.*+',
  'finance/approval_mrclose/list/.*+',
  'finance/approval_po/list/.*+',
  'finance/approval_fat/list/.*+',
  'finance/manage_item/list',
  'finance/manage_itemdetail/list',
  'finance/manage_konversi/list/.*+',
  'finance/manage_itemstok/list',
  'finance/manage_stokopname/list',
  'finance/manage_adjuststok/list',
  'finance/manage_fat/list1/InvToFat',
  'finance/manage_fat/list/.*+',
  'finance/manage_fat/list2',
  'finance/manage_po/list',
  'finance/manage_stokitem_wh/list',
  'finance/manage_stokitem_pr/list',
  'finance/approval_invoice/list/.*+',
  'finance/manage_invoice/list/.*+',
  'finance/manage_release_giro/list/.*+',
  'finance/manage_job/list',
  'finance/manage_teamproject/list',
  'finance/manage_teamproject/list/.*+',
  'finance/manage_rekening/list',
  'finance/manage_rek_perusahaan/list',
  'finance/manage_supplier/list',
  'finance/monitoring_pr/list',
  'finance/monitoring_po/list',
  'finance/monitoring_fat_detail/list',
  'finance/monitoring_mr/list/.*+',
  'finance/manage_item_po/list/.*+',
  'finance/manage_item_pr/list/All',
  'finance/manage_asset/list/.*+',
  'finance/manage_currency/list',
  'finance/monitoring_item_mi/list',
  'finance/monitoring_item_mo/list',
  'finance/manage_do/list/.*+',
  'finance/monitoring_do_detail/list',
  'finance/bankpayment/list/.*+',
  'finance/manage_retur_mo/list',
  'finance/manage_retur_po/list',
  'finance/lp_rencana_pembayaran/getlaporan',
  'finance/manage_other_charge/list',
  'finance/manage_sub_item/list',
  'finance/request_approve/list/.*+',
  'finance/manage_coa/list',
  'finance/manage_transaksi/list/.*+',
  'finance/approval_transaksi/list/.*+',
  'finance/approval_transaksi/list2/.*+',
  'finance/manage_periodeakuntansi/list',
  'finance/manage_pcoa/list',
  'finance/manage_kas/list',
  'finance/manage_kegiatan/list',
  'finance/manage_jurnal/list',
  'finance/manage_jurnal/list2',
  'finance/approval_cad/list/.*+',
  'finance/approval_exr/list/.*+',
  'finance/approval_pettycash/list/.*+',
  'finance/approval_rfp/list/.*+',
  'finance/manage_picppbank/list',
  'finance/manage_limitcad/list',
  'finance/manage_pettycash/list',
  'finance/manage_rfp/list',
  'finance/manage_rfp_kasbesar/list',
  'finance/manage_cad/list',
  'finance/manage_exr/list',
  'finance/approval_payment_schedule/list/.*+',
  'finance/approval_payment_schedule/totalkan',
  'finance/manage_customer/list',
  'finance/monitoring_ca_will_lpj/list',
  'finance/manage_invoice_sales/list',
  'finance/manage_kategori_pajak/list',
  'finance/manage_dokumen_pajak/list',
  'finance/manage_bukubillyet/list',
  'finance/manage_billyet/list/.*+',
  'finance/manage_billyet/list2/.*+',
  'finance/manage_bukti_potong/list',
  'finance/manage_ssp/list',
  'finance/approval_bank_payment/list/.*+',
  'finance/approval_bank_payment/list2/.*+',
  'finance/approval_cash_payment/list/.*+',
  'finance/approval_cash_receive/list/.*+',
  'finance/manage_item_pajak/list',
  'finance/manage_item_kegiatan/list',
  'finance/manage_saldoawal/list',
  'finance/approval_jurnal_gaji/list/.*+',

  # Asset
  'asset/manage_lokasi/list',
  'asset/manage_gedung/list',
  'asset/manage_ruang/list',
  'asset/manage_rak/list',
  'asset/manage_asset/list/.*+',
  'asset/manage_asset_hapus/list',
  'asset/riwayat_storage/list',
  'asset/riwayat_job/list',
  'asset/manage_pinjam/list/.*+',
  'asset/manage_kembali/list',
  'asset/manage_rental_kontrak/list',
  'asset/monitoring_rental_asset/list',
  'asset/approval_mr/list/.*+',
  'asset/approval_pr/list/.*+',
  'asset/approval_pinjam/list/.*+',
  'asset/approval_kembali/list/.*+',
  'asset/notifikasi/list',
  'asset/notifikasi/cek_notif',
  'asset/manage_jaminan/leasing/list',
  'asset/manage_jaminan/asuransi/list',
  'asset/manage_rental_asset/list/.*+',
  'asset/manage_itemdetail/list',
  'asset/manage_kategori/list',
  'asset/maintenance_dokumen/list/.*+',
  'asset/maintenance_dokumen/list',
  'asset/manage_referensi/bahan_bakar/list',
  'asset/manage_referensi/jenis_dokumen/list',
  'asset/manage_stokitem_wh/list',
  'asset/manage_stokitem_pr/list',
  'asset/manage_lembaga/leasing/list',
  'asset/manage_lembaga/asuransi/list',
  'asset/monitoring_po/list',
  'asset/monitoring_po_detail/list/.*+',
  'asset/manage_pinjam/list/pinjam_detail',
  'asset/manage_kembali/list/kembali_detail',
  'asset/surat_aset_approval/list',
  'asset/surat_aset_template/list',
  'asset/surat_kuasa/list',
  'asset/surat_pelepasan_hak_kendaraan/list',
  'asset/surat_perbedaan_harga/list',
  'asset/surat_penghapusan_denda/list',
  'asset/surat_kalibrasi_alat/list',
  'asset/manage_jual/list',
  'asset/approval_jual/list/.*+',
  'asset/monitoring_rental_asset/add/.*+',
  'asset/monitoring_rental_asset/import',
  'asset/manage_item/list',

  # Receptionist
  'receptionist/notifikasi/list',
  'receptionist/notifikasi/cek_notif',
  'receptionist/manage_ttdokumen/list/.*+',

  # MR
  'mr/manage_notifikasi/list',
  'mr/notifikasi/cek_notif',
  'mr/lap_request/excel',
  'mr/lap_mutu/excel',
  'mr/manage_kategori/list',
  'mr/manage_item/list',
  'mr/manage_itemdetail/list',

  # Direktur
  'direktur/notifikasi/list',
  'direktur/notifikasi/cek_notif',
  'direktur/approval_cad/list/.*+',
  'direktur/approval_exr/list/.*+',

  # Kasir
  'kasir/notifikasi/list',
  'kasir/notifikasi/cek_notif',
  'kasir/manage_pettycash/list',
  'kasir/manage_pettycash/list2',
  'kasir/manage_pettycash/createvoucher',
  'kasir/manage_transaksi_cashpayment/list/.*+',
  'kasir/manage_transaksi_cashreceive/list/.*+',
  'kasir/manage_transaksi_bankpayment/list/.*+',
  'kasir/manage_transaksi_bankreceive/list/.*+',
  'kasir/approval_cad/list/.*+',
  'kasir/approval_exr/list/.*+',
  'kasir/manage_cad/list',
  'kasir/manage_cad/list2',
  'kasir/manage_cad/list3',
  'kasir/manage_exr/list',
  'kasir/manage_exr/list2',
  'kasir/manage_exr/list3',
  'kasir/manage_rfp/list',
  'kasir/manage_rfp/list2',
  'kasir/manage_rfp/list3',
  'kasir/approval_rfp/list/.*+',
  'kasir/approval_rfp_kasbesar/list/.*+',
  'kasir/approval_pettycash/list/.*+',
  'kasir/manage_jurnal/list',
  'kasir/monitoring_dokumen_kasbank/list/.*+',
  'kasir/monitoring_ca_will_lpj/list',
  'kasir/penerimaan_invoice/list',
  'kasir/manage_payment_fat/list/.*',
  'kasir/manage_payment_nonfat/list/.*',
  'kasir/manage_payment_pettycash/list/.*',
  'kasir/manage_payment_pettycash/list2/.*',
  'kasir/manage_payment_pettycash/list3/.*',
  'kasir/bankpayment/list/.*',
  'kasir/manage_bukubillyet/list',
  'kasir/manage_billyet/list/.*+',
  'kasir/manage_billyet/list2/.*+',


  //exception new format
  'dir/api/.*+',

  'fetch/.*+',

  //exception untuk mobile API
  'hrdmobile/.*+',
);

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';
